name : Gerar Dados

on :
  schedule: # executa a cada 12 horas
    -cron: " * */12 * * * "
  workflow_dispatch:

jobs :
  build :
    name : Jobs para atualizar dados
    runs-on : ubuntu-latest
    steps :
      # Animação de cobra
      - uses : Platane/snk@master
        id : cobra-gif
        com :
          github_user_name : akoruudev
          svg_out_path : dist/github-contribution-grid-snake.svg

      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
          target_branch : saída
          build_dir : dist
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
